language: node_js
sudo: false
node_js:
  - 0.10
  - 0.12
  - 4
env:
  - NODE_ENV=travis
matrix:
  allow_failures:
    - node_js: 4
services:
  - mongodb
before_install:
  - gem update --system
  - gem install sass --version "=3.3.7"
  - npm i nsp -g
after_script:
  - nsp audit-package
  - grunt coverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/249daf9851ea4776f34e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
cache:
  apt: true
  directories:
  - node_modules/
  - public/lib/
